# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75df0496ecf43f9f005aa14adf7cc11ebb22c25f3c0d7e2635b99932248e12f21ed7ee74dd566306fd3f37da8ec43cc68644a37e3141d74a037f1634630ad81

test:
  secret_key_base: 05c1749ec1a4cc1d53d1d0beec5c3d1695067d573e9dc2f6c30d7311535f5ddd098cc21c5161fb5acdc74aa3452289b58fef67a742797e7e146806adc6273ef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
